SET NAMES utf8mb4;

UPDATE languageitem
SET Name = '수련용 스태프'
WHERE Language = 'KR'
  AND TranslationId = 'training_staff';

DELETE FROM languagenpc
WHERE Language = 'KR'
  AND TranslationId IN (
    'npc.new_mob',
    'npc.spraggon',
    'npc.water_beetle',
    'npc.large_frog',
    'npc.small_hill_cat',
    'npc.mudman',
    'npc.hill_toad',
    'npc.rowdy',
    'npc.water_beetle_larva',
    'npc.bandit',
    'npc.feccan',
    'npc.skeletal_pawn',
    'npc.water_beetle_collector',
    'npc.green_snake',
    'npc.eirebug',
    'npc.lugradan_whelp',
    'npc.lunantishee',
    'npc.spriggarn',
    'npc.villainous_youth',
    'npc.young_grendelorm',
    'npc.badger_cub',
    'npc.pine_imp',
    'npc.hill_person',
    'npc.huldu_stalker',
    'npc.orchard_nipper',
    'npc.spindly_rock_crab',
    'npc.giant_spider',
    'npc.rattling_skeleton',
    'npc.envy_drakeling',
    'npc.ambient_wisp',
    'npc.emerald_snake',
    'npc.river_spriteling',
    'npc.huldu_hunter',
    'npc.death_grip_vines',
    'npc.undead_filidh',
    'npc.carrion_crawler',
    'npc.brownie',
    'npc.small_bear',
    'npc.annoying_lucradan',
    'npc.lough_wolf',
    'npc.vein_spider',
    'npc.water_strider',
    'npc.devout_filidh',
    'npc.skeletal_minion',
    'npc.black_bear',
    'npc.young_boar',
    'npc.spraggonoll',
    'npc.ambient_pixie',
    'npc.hobgoblin_snagger',
    'npc.worker_ant',
    'npc.haunt',
    'npc.spriggarn_elder',
    'npc.water_leaper',
    'npc.hobgoblin_prankster',
    'npc.rock_crab',
    'npc.swamp_rat',
    'npc.skeleton',
    'npc.slough_serpent',
    'npc.hill_cat',
    'npc.lake_adder',
    'npc.lupine_snarler',
    'npc.sapherd',
    'npc.wild_lucradan',
    'npc.rot_worm',
    'npc.brownie_nomad',
    'npc.water_snake',
    'npc.filidh',
    'npc.large_skeleton',
    'npc.vein_spiderling',
    'npc.wild_crouch',
    'npc.boulderling',
    'npc.decayed_zombie',
    'npc.dappled_lynx_cub',
    'npc.roaming_dirge',
    'npc.wood_eater',
    'npc.bandit_henchman',
    'npc.creeping_crud',
    'npc.gray_wolf',
    'npc.lough_wolf_cadger',
    'npc.tawny_lynx',
    'npc.urchin_hooligan',
    'npc.biting_insect',
    'npc.muryan',
    'npc.anger_sprite',
    'npc.catty_sylvanshade',
    'npc.army_ant_worker',
    'npc.shambler',
    'npc.badger',
    'npc.red_wolfhound',
    'npc.rock_sheerie',
    'npc.mammoth_calf',
    'npc.dew_sheerie',
    'npc.morvalt_krigsman',
    'npc.tomb_raider',
    'npc.wolf_nipper',
    'npc.hungry_shriller',
    'npc.fishing_bear_forager',
    'npc.oaken_fellwood',
    'npc.cniogcrag_infester',
    'npc.shrieking_willow',
    'npc.sand_jelly',
    'npc.bogman',
    'npc.rabid_wolfhound',
    'npc.skogsfru',
    'npc.primrose',
    'npc.young_scimitar_cat',
    'npc.host_of_the_wind',
    'npc.host_of_the_earth',
    'npc.arachite_shadowslinker',
    'npc.vendo_bone_collector',
    'npc.werewolf',
    'npc.parthanan',
    'npc.blackthorn',
    'npc.maundering_sporite',
    'npc.mist_sprite',
    'npc.black_mauler',
    'npc.tomte_thug',
    'npc.cluricaun_trip',
    'npc.wildling',
    'npc.ghoul_knight',
    'npc.fragile_skeleton',
    'npc.forest_ettin',
    'npc.corpse_flicker',
    'npc.ashen_fellwood',
    'npc.urchin_rabblerouser',
    'npc.apprentice_necyomancer',
    'npc.mora_dancer',
    'npc.phantom_page',
    'npc.sveawolf_mother',
    'npc.nordic_dirge',
    'npc.ghastly_siabra',
    'npc.spraggonilt',
    'npc.black_willow_fellwood',
    'npc.death_stalker',
    'npc.grass_sheerie',
    'npc.giant_water_leaper',
    'npc.large_sveawolf',
    'npc.vendo_warrior',
    'npc.bogman_grappler',
    'npc.rat_boy',
    'npc.dergan_enchanter',
    'npc.ebony_fellwood',
    'npc.fading_spirit',
    'npc.giant_dragonfly',
    'npc.luricaduane',
    'npc.putrid_zombie'
  );

INSERT INTO languagenpc
  (LanguageNPC_ID, TranslationId, Language, Name, Suffix, GuildName, ExamineArticle, MessageArticle, Tag, LastTimeRowUpdated)
VALUES
  (UUID(), 'npc.new_mob', 'KR', '새 몹', NULL, NULL, NULL, NULL, 'korean-localization-starter-mobs', NOW()),
  (UUID(), 'npc.spraggon', 'KR', '스프라곤', NULL, NULL, NULL, NULL, 'korean-localization-starter-mobs', NOW()),
  (UUID(), 'npc.water_beetle', 'KR', '물방개', NULL, NULL, NULL, NULL, 'korean-localization-starter-mobs', NOW()),
  (UUID(), 'npc.large_frog', 'KR', '큰 개구리', NULL, NULL, NULL, NULL, 'korean-localization-starter-mobs', NOW()),
  (UUID(), 'npc.small_hill_cat', 'KR', '작은 언덕고양이', NULL, NULL, NULL, NULL, 'korean-localization-starter-mobs', NOW()),
  (UUID(), 'npc.mudman', 'KR', '머드맨', NULL, NULL, NULL, NULL, 'korean-localization-starter-mobs', NOW()),
  (UUID(), 'npc.hill_toad', 'KR', '언덕 두꺼비', NULL, NULL, NULL, NULL, 'korean-localization-starter-mobs', NOW()),
  (UUID(), 'npc.rowdy', 'KR', '난동꾼', NULL, NULL, NULL, NULL, 'korean-localization-starter-mobs', NOW()),
  (UUID(), 'npc.water_beetle_larva', 'KR', '물방개 유충', NULL, NULL, NULL, NULL, 'korean-localization-starter-mobs', NOW()),
  (UUID(), 'npc.bandit', 'KR', '도적', NULL, NULL, NULL, NULL, 'korean-localization-starter-mobs', NOW()),
  (UUID(), 'npc.feccan', 'KR', '페칸', NULL, NULL, NULL, NULL, 'korean-localization-starter-mobs', NOW()),
  (UUID(), 'npc.skeletal_pawn', 'KR', '해골 하수인', NULL, NULL, NULL, NULL, 'korean-localization-starter-mobs', NOW()),
  (UUID(), 'npc.water_beetle_collector', 'KR', '물방개 수집꾼', NULL, NULL, NULL, NULL, 'korean-localization-starter-mobs', NOW()),
  (UUID(), 'npc.green_snake', 'KR', '녹색 뱀', NULL, NULL, NULL, NULL, 'korean-localization-starter-mobs', NOW()),
  (UUID(), 'npc.eirebug', 'KR', '에이르버그', NULL, NULL, NULL, NULL, 'korean-localization-starter-mobs', NOW()),
  (UUID(), 'npc.lugradan_whelp', 'KR', '루그라단 새끼', NULL, NULL, NULL, NULL, 'korean-localization-starter-mobs', NOW()),
  (UUID(), 'npc.lunantishee', 'KR', '루난티시', NULL, NULL, NULL, NULL, 'korean-localization-starter-mobs', NOW()),
  (UUID(), 'npc.spriggarn', 'KR', '스프리간', NULL, NULL, NULL, NULL, 'korean-localization-starter-mobs', NOW()),
  (UUID(), 'npc.villainous_youth', 'KR', '악한 청년', NULL, NULL, NULL, NULL, 'korean-localization-starter-mobs', NOW()),
  (UUID(), 'npc.young_grendelorm', 'KR', '어린 그렌델오름', NULL, NULL, NULL, NULL, 'korean-localization-starter-mobs', NOW()),
  (UUID(), 'npc.badger_cub', 'KR', '오소리 새끼', NULL, NULL, NULL, NULL, 'korean-localization-starter-mobs', NOW()),
  (UUID(), 'npc.pine_imp', 'KR', '소나무 임프', NULL, NULL, NULL, NULL, 'korean-localization-starter-mobs', NOW()),
  (UUID(), 'npc.hill_person', 'KR', '언덕 사람', NULL, NULL, NULL, NULL, 'korean-localization-starter-mobs', NOW()),
  (UUID(), 'npc.huldu_stalker', 'KR', '훌두 추적자', NULL, NULL, NULL, NULL, 'korean-localization-starter-mobs', NOW()),
  (UUID(), 'npc.orchard_nipper', 'KR', '과수원 니퍼', NULL, NULL, NULL, NULL, 'korean-localization-starter-mobs', NOW()),
  (UUID(), 'npc.spindly_rock_crab', 'KR', '마른 바위게', NULL, NULL, NULL, NULL, 'korean-localization-starter-mobs', NOW()),
  (UUID(), 'npc.giant_spider', 'KR', '거대 거미', NULL, NULL, NULL, NULL, 'korean-localization-starter-mobs', NOW()),
  (UUID(), 'npc.rattling_skeleton', 'KR', '덜그럭 해골', NULL, NULL, NULL, NULL, 'korean-localization-starter-mobs', NOW()),
  (UUID(), 'npc.envy_drakeling', 'KR', '질투의 드레이크 새끼', NULL, NULL, NULL, NULL, 'korean-localization-starter-mobs', NOW()),
  (UUID(), 'npc.ambient_wisp', 'KR', '떠도는 위습', NULL, NULL, NULL, NULL, 'korean-localization-starter-mobs', NOW()),
  (UUID(), 'npc.emerald_snake', 'KR', '에메랄드 뱀', NULL, NULL, NULL, NULL, 'korean-localization-starter-mobs', NOW()),
  (UUID(), 'npc.river_spriteling', 'KR', '강의 작은 정령', NULL, NULL, NULL, NULL, 'korean-localization-starter-mobs', NOW()),
  (UUID(), 'npc.huldu_hunter', 'KR', '훌두 사냥꾼', NULL, NULL, NULL, NULL, 'korean-localization-starter-mobs', NOW()),
  (UUID(), 'npc.death_grip_vines', 'KR', '죽음손아귀 덩굴', NULL, NULL, NULL, NULL, 'korean-localization-starter-mobs', NOW()),
  (UUID(), 'npc.undead_filidh', 'KR', '언데드 필리드', NULL, NULL, NULL, NULL, 'korean-localization-starter-mobs', NOW()),
  (UUID(), 'npc.carrion_crawler', 'KR', '시체 크롤러', NULL, NULL, NULL, NULL, 'korean-localization-starter-mobs', NOW()),
  (UUID(), 'npc.brownie', 'KR', '브라우니', NULL, NULL, NULL, NULL, 'korean-localization-starter-mobs', NOW()),
  (UUID(), 'npc.small_bear', 'KR', '작은 곰', NULL, NULL, NULL, NULL, 'korean-localization-starter-mobs', NOW()),
  (UUID(), 'npc.annoying_lucradan', 'KR', '성가신 루크라단', NULL, NULL, NULL, NULL, 'korean-localization-starter-mobs', NOW()),
  (UUID(), 'npc.lough_wolf', 'KR', '러프 늑대', NULL, NULL, NULL, NULL, 'korean-localization-starter-mobs', NOW()),
  (UUID(), 'npc.vein_spider', 'KR', '광맥 거미', NULL, NULL, NULL, NULL, 'korean-localization-starter-mobs', NOW()),
  (UUID(), 'npc.water_strider', 'KR', '물소금쟁이', NULL, NULL, NULL, NULL, 'korean-localization-starter-mobs', NOW()),
  (UUID(), 'npc.devout_filidh', 'KR', '독실한 필리드', NULL, NULL, NULL, NULL, 'korean-localization-starter-mobs', NOW()),
  (UUID(), 'npc.skeletal_minion', 'KR', '해골 부하', NULL, NULL, NULL, NULL, 'korean-localization-starter-mobs', NOW()),
  (UUID(), 'npc.black_bear', 'KR', '검은 곰', NULL, NULL, NULL, NULL, 'korean-localization-starter-mobs', NOW()),
  (UUID(), 'npc.young_boar', 'KR', '어린 멧돼지', NULL, NULL, NULL, NULL, 'korean-localization-starter-mobs', NOW()),
  (UUID(), 'npc.spraggonoll', 'KR', '스프라곤놀', NULL, NULL, NULL, NULL, 'korean-localization-starter-mobs', NOW()),
  (UUID(), 'npc.ambient_pixie', 'KR', '떠도는 픽시', NULL, NULL, NULL, NULL, 'korean-localization-starter-mobs', NOW()),
  (UUID(), 'npc.hobgoblin_snagger', 'KR', '홉고블린 스내거', NULL, NULL, NULL, NULL, 'korean-localization-starter-mobs', NOW()),
  (UUID(), 'npc.worker_ant', 'KR', '일개미', NULL, NULL, NULL, NULL, 'korean-localization-starter-mobs', NOW()),
  (UUID(), 'npc.haunt', 'KR', '유령', NULL, NULL, NULL, NULL, 'korean-localization-starter-mobs', NOW()),
  (UUID(), 'npc.spriggarn_elder', 'KR', '스프리간 장로', NULL, NULL, NULL, NULL, 'korean-localization-starter-mobs', NOW()),
  (UUID(), 'npc.water_leaper', 'KR', '워터 리퍼', NULL, NULL, NULL, NULL, 'korean-localization-starter-mobs', NOW()),
  (UUID(), 'npc.hobgoblin_prankster', 'KR', '홉고블린 장난꾼', NULL, NULL, NULL, NULL, 'korean-localization-starter-mobs', NOW()),
  (UUID(), 'npc.rock_crab', 'KR', '바위게', NULL, NULL, NULL, NULL, 'korean-localization-starter-mobs', NOW()),
  (UUID(), 'npc.swamp_rat', 'KR', '늪쥐', NULL, NULL, NULL, NULL, 'korean-localization-starter-mobs', NOW()),
  (UUID(), 'npc.skeleton', 'KR', '해골', NULL, NULL, NULL, NULL, 'korean-localization-starter-mobs', NOW()),
  (UUID(), 'npc.slough_serpent', 'KR', '늪지 뱀', NULL, NULL, NULL, NULL, 'korean-localization-starter-mobs', NOW()),
  (UUID(), 'npc.hill_cat', 'KR', '언덕고양이', NULL, NULL, NULL, NULL, 'korean-localization-starter-mobs', NOW()),
  (UUID(), 'npc.lake_adder', 'KR', '호수 독사', NULL, NULL, NULL, NULL, 'korean-localization-starter-mobs', NOW()),
  (UUID(), 'npc.lupine_snarler', 'KR', '루핀 스날러', NULL, NULL, NULL, NULL, 'korean-localization-starter-mobs', NOW()),
  (UUID(), 'npc.sapherd', 'KR', '사퍼드', NULL, NULL, NULL, NULL, 'korean-localization-starter-mobs', NOW()),
  (UUID(), 'npc.wild_lucradan', 'KR', '야생 루크라단', NULL, NULL, NULL, NULL, 'korean-localization-starter-mobs', NOW()),
  (UUID(), 'npc.rot_worm', 'KR', '부패 벌레', NULL, NULL, NULL, NULL, 'korean-localization-starter-mobs', NOW()),
  (UUID(), 'npc.brownie_nomad', 'KR', '브라우니 유목민', NULL, NULL, NULL, NULL, 'korean-localization-starter-mobs', NOW()),
  (UUID(), 'npc.water_snake', 'KR', '물뱀', NULL, NULL, NULL, NULL, 'korean-localization-starter-mobs', NOW()),
  (UUID(), 'npc.filidh', 'KR', '필리드', NULL, NULL, NULL, NULL, 'korean-localization-starter-mobs', NOW()),
  (UUID(), 'npc.large_skeleton', 'KR', '큰 해골', NULL, NULL, NULL, NULL, 'korean-localization-starter-mobs', NOW()),
  (UUID(), 'npc.vein_spiderling', 'KR', '작은 광맥 거미', NULL, NULL, NULL, NULL, 'korean-localization-starter-mobs', NOW()),
  (UUID(), 'npc.wild_crouch', 'KR', '야생 크라우치', NULL, NULL, NULL, NULL, 'korean-localization-starter-mobs', NOW()),
  (UUID(), 'npc.boulderling', 'KR', '작은 바위정령', NULL, NULL, NULL, NULL, 'korean-localization-starter-mobs', NOW()),
  (UUID(), 'npc.decayed_zombie', 'KR', '부패한 좀비', NULL, NULL, NULL, NULL, 'korean-localization-starter-mobs', NOW()),
  (UUID(), 'npc.dappled_lynx_cub', 'KR', '얼룩 스라소니 새끼', NULL, NULL, NULL, NULL, 'korean-localization-starter-mobs', NOW()),
  (UUID(), 'npc.roaming_dirge', 'KR', '떠도는 더지', NULL, NULL, NULL, NULL, 'korean-localization-starter-mobs', NOW()),
  (UUID(), 'npc.wood_eater', 'KR', '나무먹보', NULL, NULL, NULL, NULL, 'korean-localization-starter-mobs', NOW()),
  (UUID(), 'npc.bandit_henchman', 'KR', '도적 부하', NULL, NULL, NULL, NULL, 'korean-localization-starter-mobs', NOW()),
  (UUID(), 'npc.creeping_crud', 'KR', '기어다니는 오물', NULL, NULL, NULL, NULL, 'korean-localization-starter-mobs', NOW()),
  (UUID(), 'npc.gray_wolf', 'KR', '회색 늑대', NULL, NULL, NULL, NULL, 'korean-localization-starter-mobs', NOW()),
  (UUID(), 'npc.lough_wolf_cadger', 'KR', '러프 늑대 캐저', NULL, NULL, NULL, NULL, 'korean-localization-starter-mobs', NOW()),
  (UUID(), 'npc.tawny_lynx', 'KR', '황갈색 스라소니', NULL, NULL, NULL, NULL, 'korean-localization-starter-mobs', NOW()),
  (UUID(), 'npc.urchin_hooligan', 'KR', '어친 훌리건', NULL, NULL, NULL, NULL, 'korean-localization-starter-mobs', NOW()),
  (UUID(), 'npc.biting_insect', 'KR', '무는 벌레', NULL, NULL, NULL, NULL, 'korean-localization-starter-mobs', NOW()),
  (UUID(), 'npc.muryan', 'KR', '뮤리안', NULL, NULL, NULL, NULL, 'korean-localization-starter-mobs', NOW()),
  (UUID(), 'npc.anger_sprite', 'KR', '분노 스프라이트', NULL, NULL, NULL, NULL, 'korean-localization-starter-mobs', NOW()),
  (UUID(), 'npc.catty_sylvanshade', 'KR', '새침한 실반셰이드', NULL, NULL, NULL, NULL, 'korean-localization-starter-mobs', NOW()),
  (UUID(), 'npc.army_ant_worker', 'KR', '군대개미 일꾼', NULL, NULL, NULL, NULL, 'korean-localization-starter-mobs', NOW()),
  (UUID(), 'npc.shambler', 'KR', '샴블러', NULL, NULL, NULL, NULL, 'korean-localization-starter-mobs', NOW()),
  (UUID(), 'npc.badger', 'KR', '오소리', NULL, NULL, NULL, NULL, 'korean-localization-starter-mobs', NOW()),
  (UUID(), 'npc.red_wolfhound', 'KR', '붉은 울프하운드', NULL, NULL, NULL, NULL, 'korean-localization-starter-mobs', NOW()),
  (UUID(), 'npc.rock_sheerie', 'KR', '바위 쉬리', NULL, NULL, NULL, NULL, 'korean-localization-starter-mobs', NOW()),
  (UUID(), 'npc.mammoth_calf', 'KR', '매머드 새끼', NULL, NULL, NULL, NULL, 'korean-localization-starter-mobs', NOW()),
  (UUID(), 'npc.dew_sheerie', 'KR', '이슬 쉬리', NULL, NULL, NULL, NULL, 'korean-localization-starter-mobs', NOW()),
  (UUID(), 'npc.morvalt_krigsman', 'KR', '모르발트 크리그스맨', NULL, NULL, NULL, NULL, 'korean-localization-starter-mobs', NOW()),
  (UUID(), 'npc.tomb_raider', 'KR', '무덤 약탈자', NULL, NULL, NULL, NULL, 'korean-localization-starter-mobs', NOW()),
  (UUID(), 'npc.wolf_nipper', 'KR', '늑대 니퍼', NULL, NULL, NULL, NULL, 'korean-localization-starter-mobs', NOW()),
  (UUID(), 'npc.hungry_shriller', 'KR', '굶주린 슈릴러', NULL, NULL, NULL, NULL, 'korean-localization-starter-mobs', NOW()),
  (UUID(), 'npc.fishing_bear_forager', 'KR', '피싱 베어 포리저', NULL, NULL, NULL, NULL, 'korean-localization-starter-mobs', NOW()),
  (UUID(), 'npc.oaken_fellwood', 'KR', '오큰 펠우드', NULL, NULL, NULL, NULL, 'korean-localization-starter-mobs', NOW()),
  (UUID(), 'npc.cniogcrag_infester', 'KR', '크니오그크래그 감염체', NULL, NULL, NULL, NULL, 'korean-localization-starter-mobs', NOW()),
  (UUID(), 'npc.shrieking_willow', 'KR', '비명 버드나무', NULL, NULL, NULL, NULL, 'korean-localization-starter-mobs', NOW()),
  (UUID(), 'npc.sand_jelly', 'KR', '모래 젤리', NULL, NULL, NULL, NULL, 'korean-localization-starter-mobs', NOW()),
  (UUID(), 'npc.bogman', 'KR', '보그맨', NULL, NULL, NULL, NULL, 'korean-localization-starter-mobs', NOW()),
  (UUID(), 'npc.rabid_wolfhound', 'KR', '광견 울프하운드', NULL, NULL, NULL, NULL, 'korean-localization-starter-mobs', NOW()),
  (UUID(), 'npc.skogsfru', 'KR', '스코그스프루', NULL, NULL, NULL, NULL, 'korean-localization-starter-mobs', NOW()),
  (UUID(), 'npc.primrose', 'KR', '프림로즈', NULL, NULL, NULL, NULL, 'korean-localization-starter-mobs', NOW()),
  (UUID(), 'npc.young_scimitar_cat', 'KR', '어린 시미터 캣', NULL, NULL, NULL, NULL, 'korean-localization-starter-mobs', NOW()),
  (UUID(), 'npc.host_of_the_wind', 'KR', '바람의 숙주', NULL, NULL, NULL, NULL, 'korean-localization-starter-mobs', NOW()),
  (UUID(), 'npc.host_of_the_earth', 'KR', '대지의 숙주', NULL, NULL, NULL, NULL, 'korean-localization-starter-mobs', NOW()),
  (UUID(), 'npc.arachite_shadowslinker', 'KR', '아라카이트 섀도우슬링커', NULL, NULL, NULL, NULL, 'korean-localization-starter-mobs', NOW()),
  (UUID(), 'npc.vendo_bone_collector', 'KR', '벤도 뼈 수집꾼', NULL, NULL, NULL, NULL, 'korean-localization-starter-mobs', NOW()),
  (UUID(), 'npc.werewolf', 'KR', '웨어울프', NULL, NULL, NULL, NULL, 'korean-localization-starter-mobs', NOW()),
  (UUID(), 'npc.parthanan', 'KR', '파르타난', NULL, NULL, NULL, NULL, 'korean-localization-starter-mobs', NOW()),
  (UUID(), 'npc.blackthorn', 'KR', '블랙쏜', NULL, NULL, NULL, NULL, 'korean-localization-starter-mobs', NOW()),
  (UUID(), 'npc.maundering_sporite', 'KR', '방황하는 스포라이트', NULL, NULL, NULL, NULL, 'korean-localization-starter-mobs', NOW()),
  (UUID(), 'npc.mist_sprite', 'KR', '안개 스프라이트', NULL, NULL, NULL, NULL, 'korean-localization-starter-mobs', NOW()),
  (UUID(), 'npc.black_mauler', 'KR', '검은 마울러', NULL, NULL, NULL, NULL, 'korean-localization-starter-mobs', NOW()),
  (UUID(), 'npc.tomte_thug', 'KR', '톰테 폭력배', NULL, NULL, NULL, NULL, 'korean-localization-starter-mobs', NOW()),
  (UUID(), 'npc.cluricaun_trip', 'KR', '클루리컨 트립', NULL, NULL, NULL, NULL, 'korean-localization-starter-mobs', NOW()),
  (UUID(), 'npc.wildling', 'KR', '와일들링', NULL, NULL, NULL, NULL, 'korean-localization-starter-mobs', NOW()),
  (UUID(), 'npc.ghoul_knight', 'KR', '구울 기사', NULL, NULL, NULL, NULL, 'korean-localization-starter-mobs', NOW()),
  (UUID(), 'npc.fragile_skeleton', 'KR', '약한 해골', NULL, NULL, NULL, NULL, 'korean-localization-starter-mobs', NOW()),
  (UUID(), 'npc.forest_ettin', 'KR', '숲 에틴', NULL, NULL, NULL, NULL, 'korean-localization-starter-mobs', NOW()),
  (UUID(), 'npc.corpse_flicker', 'KR', '시체 플리커', NULL, NULL, NULL, NULL, 'korean-localization-starter-mobs', NOW()),
  (UUID(), 'npc.ashen_fellwood', 'KR', '잿빛 펠우드', NULL, NULL, NULL, NULL, 'korean-localization-starter-mobs', NOW()),
  (UUID(), 'npc.urchin_rabblerouser', 'KR', '어친 선동꾼', NULL, NULL, NULL, NULL, 'korean-localization-starter-mobs', NOW()),
  (UUID(), 'npc.apprentice_necyomancer', 'KR', '견습 네시오맨서', NULL, NULL, NULL, NULL, 'korean-localization-starter-mobs', NOW()),
  (UUID(), 'npc.mora_dancer', 'KR', '모라 댄서', NULL, NULL, NULL, NULL, 'korean-localization-starter-mobs', NOW()),
  (UUID(), 'npc.phantom_page', 'KR', '팬텀 페이지', NULL, NULL, NULL, NULL, 'korean-localization-starter-mobs', NOW()),
  (UUID(), 'npc.sveawolf_mother', 'KR', '스베아울프 어미', NULL, NULL, NULL, NULL, 'korean-localization-starter-mobs', NOW()),
  (UUID(), 'npc.nordic_dirge', 'KR', '노르딕 더지', NULL, NULL, NULL, NULL, 'korean-localization-starter-mobs', NOW()),
  (UUID(), 'npc.ghastly_siabra', 'KR', '섬뜩한 시아브라', NULL, NULL, NULL, NULL, 'korean-localization-starter-mobs', NOW()),
  (UUID(), 'npc.spraggonilt', 'KR', '스프라곤일트', NULL, NULL, NULL, NULL, 'korean-localization-starter-mobs', NOW()),
  (UUID(), 'npc.black_willow_fellwood', 'KR', '검은 버드나무 펠우드', NULL, NULL, NULL, NULL, 'korean-localization-starter-mobs', NOW()),
  (UUID(), 'npc.death_stalker', 'KR', '죽음 추적자', NULL, NULL, NULL, NULL, 'korean-localization-starter-mobs', NOW()),
  (UUID(), 'npc.grass_sheerie', 'KR', '풀 쉬리', NULL, NULL, NULL, NULL, 'korean-localization-starter-mobs', NOW()),
  (UUID(), 'npc.giant_water_leaper', 'KR', '거대 워터 리퍼', NULL, NULL, NULL, NULL, 'korean-localization-starter-mobs', NOW()),
  (UUID(), 'npc.large_sveawolf', 'KR', '큰 스베아울프', NULL, NULL, NULL, NULL, 'korean-localization-starter-mobs', NOW()),
  (UUID(), 'npc.vendo_warrior', 'KR', '벤도 전사', NULL, NULL, NULL, NULL, 'korean-localization-starter-mobs', NOW()),
  (UUID(), 'npc.bogman_grappler', 'KR', '보그맨 그래플러', NULL, NULL, NULL, NULL, 'korean-localization-starter-mobs', NOW()),
  (UUID(), 'npc.rat_boy', 'KR', '랫 보이', NULL, NULL, NULL, NULL, 'korean-localization-starter-mobs', NOW()),
  (UUID(), 'npc.dergan_enchanter', 'KR', '더건 인챈터', NULL, NULL, NULL, NULL, 'korean-localization-starter-mobs', NOW()),
  (UUID(), 'npc.ebony_fellwood', 'KR', '흑단 펠우드', NULL, NULL, NULL, NULL, 'korean-localization-starter-mobs', NOW()),
  (UUID(), 'npc.fading_spirit', 'KR', '희미해지는 영혼', NULL, NULL, NULL, NULL, 'korean-localization-starter-mobs', NOW()),
  (UUID(), 'npc.giant_dragonfly', 'KR', '거대 잠자리', NULL, NULL, NULL, NULL, 'korean-localization-starter-mobs', NOW()),
  (UUID(), 'npc.luricaduane', 'KR', '루리카두안', NULL, NULL, NULL, NULL, 'korean-localization-starter-mobs', NOW()),
  (UUID(), 'npc.putrid_zombie', 'KR', '썩은 좀비', NULL, NULL, NULL, NULL, 'korean-localization-starter-mobs', NOW());
